# Generated by Django 2.2.2 on 2019-06-28 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_asset_type', models.SmallIntegerField(choices=[(0, '阿里云'), (1, '用友云')], default=0, verbose_name='服务器类型')),
                ('sub_BusinessUnit_type', models.SmallIntegerField(choices=[(0, '友报账'), (1, '友帐表'), (2, '友报表'), (3, '电子档案')], default=0, verbose_name='产品线')),
                ('hostname', models.CharField(blank=True, max_length=128, null=True, verbose_name='主机名')),
                ('ip_addr', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP_addr')),
                ('cpu', models.IntegerField(default=1, verbose_name='cpu')),
                ('mem', models.IntegerField(default=1, verbose_name='mem')),
                ('sys_disk', models.IntegerField(default=1, verbose_name='sys_disk')),
                ('data_disk', models.IntegerField(default=1, verbose_name='data_disk')),
                ('account', models.CharField(blank=True, max_length=64, null=True, verbose_name='account')),
                ('password', models.CharField(blank=True, max_length=64, null=True, verbose_name='password')),
            ],
            options={
                'verbose_name': '服务器',
                'verbose_name_plural': '服务器',
            },
        ),
        migrations.DeleteModel(
            name='BusinessUnit',
        ),
    ]
